import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" scroll-behavior = "smooth"
    
    >
            
            <body 
            className="bg-cover bg-center bg-no-repeat" 
            style={
              { backgroundImage: 'url(./images/background.jpg)' }
              }
              >

        
        <script src="https://kit.fontawesome.com/7ed0d034af.js"></script>
          
          {children}
      </body>
    </html> 
  );
}